name: Build-Test

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install git+https://github.com/wjb-dev/haraka-runtime.git@main#egg=haraka-runtime
          pip install -e .
          pip install -r requirements.txt

      - name: Build Success
        run: echo "Build completed successfully"

      - name: Lint & Format Check
        run: |
          black --check .
          flake8 .

      - name: Verify test discovery
        run: |
          pytest --collect-only tests/

      - name: Run Unit Tests
        run: |
          pytest tests/ \
            --maxfail=1 \
            --disable-warnings -q \
            --cov=app

      - name: Enforce Coverage Threshold
        run: |
          coverage report --fail-under=80 --show-missing --skip-empty