name: Adapter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SDK & Sample Adapter
        run: |
          # Install the Haraka Runtime SDK
          pip install git+https://github.com/wjb-dev/haraka-runtime.git@main#egg=haraka-runtime
          # Install the sample adapter in editable mode
          pip install -e .
          pip install -r requirements-dev.txt

      - name: Lint & Format Check
        run: |
          black --check .
          flake8 .

      - name: Verify test discovery
        run: |
          pytest --collect-only tests/

      - name: Run tests & coverage
        run: |
          pytest tests/ \
            --maxfail=1 \
            --disable-warnings -q \
            --cov=app \
            --cov-report=term-missing \


      - name: Enforce Coverage Threshold
        run: |
          coverage report --fail-under=80
