name: Publish Docker Image

on:
  workflow_run:
    workflows:
      - Test       # This matches the "name:" field in the Test workflow (test.yaml)
    types:
      - completed

env:
  SERVICE_NAME: haraka-demo  # Adjust this to match your service name
  REGISTRY_HOST: wjbdev
  VERSION: 0.1.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:latest