# .github/workflows/publish-docker.yaml
name: Publish Docker Image

on:
  workflow_call:
    inputs:
      version:
        description: 'Semantic version (e.g. 0.1.0)'
        required: true
        type: string
      keep_last_n:
        description: 'How many tags to keep (default=5)'
        required: false
        default: 5
        type: number
    secrets:
      DOCKERHUB_TOKEN:
        required: true

env:
  SERVICE_NAME: haraka-demo
  DOCKERHUB_USERNAME: wjbdev
  REGISTRY: docker.io
  REGISTRY_HOST: wjbdev

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }}
      keep_last_n: ${{ inputs.keep_last_n }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:${{ github.ref_name || env.VERSION }}
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:latest

  retention-list:
    name: Retention Policy – List & Sort Tags
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      KEEP_LAST_N: ${{ needs.build-and-push.outputs.keep_last_n }}
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch all tags from Docker Hub
        id: fetch
        run: |
          echo "› Fetching tags for $DOCKERHUB_USERNAME/$SERVICE_NAME"
          curl -s -u "$DOCKERHUB_USERNAME:$TOKEN" \
            "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/$SERVICE_NAME/tags/?page_size=100" \
            > all-tags.json
          echo "::setOutput name=data::$(jq -c '.results' all-tags.json)"

      - name: Sort tags by last_updated
        id: sort
        run: |
          mapfile -t sorted < <(
            jq -r '.[] | "\(.last_updated) \(.name)"' <<<"${{ steps.fetch.outputs.data }}" \
              | sort \
              | awk '{print $2}'
          )
          echo "All tags (oldest→newest):"
          printf " • %s\n" "${sorted[@]}"

          start=$(( ${#sorted[@]} - KEEP_LAST_N ))
          if [ $start -lt 0 ]; then start=0; fi
          recent=( "${sorted[@]:$start}" )
          echo
          echo "Most recent $KEEP_LAST_N tags:"
          printf " • %s\n" "${recent[@]}"

          echo "::setOutput name=all::${sorted[*]}"
          echo "::setOutput name=recent::${recent[*]}"

  prune-old-tags:
    name: Retention Policy – Prune Old Tags
    needs: retention-list
    runs-on: ubuntu-latest
    env:
      KEEP_LAST_N: ${{ needs.build-and-push.outputs.keep_last_n }}
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Re-fetch & sort all tags
        id: refetch
        run: |
          curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" \
            "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/$SERVICE_NAME/tags/?page_size=100" \
            | jq -r '.results[] | "\(.last_updated) \(.name)"' \
            | sort \
            | awk '{print $2}' > sorted.txt
          echo "::setOutput name=all::$(cat sorted.txt)"

      - name: Compute tags to prune
        id: compute
        run: |
          ALL=( $(cat sorted.txt) )
          TO_PRUNE_COUNT=$(( ${#ALL[@]} - KEEP_LAST_N ))
          if [ $TO_PRUNE_COUNT -le 0 ]; then
            echo "No tags to prune."
            echo "::setOutput name=to_prune::"
            exit 0
          fi
          TO_PRUNE=( "${ALL[@]:0:TO_PRUNE_COUNT}" )
          echo "Tags to prune: ${TO_PRUNE[*]}"
          echo "::setOutput name=to_prune::${TO_PRUNE[*]}"

      - name: Delete old tags
        if: ${{ steps.compute.outputs.to_prune != '' }}
        run: |
          for TAG in ${{ steps.compute.outputs.to_prune }}; do
            echo "Deleting $TAG..."
            curl -s -X DELETE -u "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" \
              "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/$SERVICE_NAME/tags/$TAG/" \
              || echo "⚠️ Failed to delete $TAG"
          done
      # —————————————————————————————————————————————
      #  Append summary to Confluence
      - name: Append Confluence Cleanup Log
        if: ${{ steps.compute.outputs.to_prune != '' }}
        env:
          BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
          USER: ${{ secrets.CONFLUENCE_USERNAME }}
          TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          DELETED: ${{ steps.compute.outputs.to_prune }}
        run: |
          TIMESTAMP=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')
          # Fetch current page version and content
          resp=$(curl -s -u "$USER:$TOKEN" \
            "$BASE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")
          ver=$(jq '.version.number' <<<"$resp")
          content=$(jq -r '.body.storage.value' <<<"$resp")
          
          # Build new log entry
          entry="<p><strong>$TIMESTAMP</strong>: deleted tags [${DELETED// /, }]</p>"
          new_content="$content$entry"
          
          # Push updated page (increment version)
          jq -n --arg id "$PAGE_ID" \
                --arg title "$(jq -r '.title' <<<"$resp")" \
                --arg body "$new_content" \
                --argjson ver $((ver + 1)) \
            '{
              id: $id,
              type: "page",
              title: $title,
              version: { number: $ver },
              body: { storage: { value: $body, representation: "storage" } }
            }' \
          | curl -s -u "$USER:$TOKEN" \
              -H "Content-Type: application/json" \
              -X PUT "$BASE_URL/rest/api/content/$PAGE_ID" \
              --data @-

      # —————————————————————————————————————————————
      #  Send Discord notification
      - name: Notify Discord
        if: ${{ steps.compute.outputs.to_prune != '' }}
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DELETED: ${{ steps.compute.outputs.to_prune }}
        run: |
          TIMESTAMP=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')
          # Build a simple embed payload
          payload=$(
            jq -nc --arg ts "$TIMESTAMP" --arg tags "$DELETED" '{
              embeds: [
                {
                  title: "Image Pruning Completed",
                  description: "Deleted tags: " + $tags,
                  timestamp: $ts,
                  color: 15158332
                }
              ]
            }'
          )
          curl -s -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            --data "$payload"
      - name: Send Hello World to Discord
        run: |
          payload=$(
            jq -n '{content: "Hello, World from GitHub Actions!"}'
          )
          curl -s -H "Content-Type: application/json" \
            --data "$payload" "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}