name: Publish Docker Image

on:
  workflow_call:
env:
  SERVICE_NAME: haraka-demo
  REGISTRY_HOST: wjbdev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:latest