name: Publish Docker Image

on:
  workflow_call:
env:
  SERVICE_NAME: haraka-demo
  REGISTRY_HOST: wjbdev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Debug Secrets
        env:
          DOCKERHUB_USERNAME: ${{ DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secret.DOCKERHUB_TOKEN }}
        run: |
          if [ -z "${{ env.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is NOT available."
            exit 1
          else
            echo "DOCKERHUB_USERNAME is available."
          fi

          if [ -z "${{ env.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is NOT available."
            exit 1
          else
            echo "DOCKERHUB_TOKEN is available."
          fi
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:latest