name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Lint & Format Check
        run: |
          black --check .
          flake8 .

      - name: Verify test discovery
        run: |
          pytest --collect-only tests/

      - name: Run Tests & Coverage
        run: |
          pytest tests/ \
            --maxfail=1 \
            --disable-warnings -q \
            --cov=app \
            --cov-report=term-missing

      - name: Enforce Coverage Threshold
        run: |
          coverage report --fail-under=80 --show-missing --skip-empty