name: Test

on:
  workflow_run:
    workflows:
      - Build     # This matches the "name:" field in the Build workflow (build.yaml)
    types:
      - completed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint & Format Check
        run: |
          black --check .
          flake8 .

      - name: Verify test discovery
        run: |
          pytest --collect-only tests/

      - name: Run Tests & Coverage
        run: |
          pytest tests/ \
            --maxfail=1 \
            --disable-warnings -q \
            --cov=app \
            --cov-report=term-missing

      - name: Enforce Coverage Threshold
        run: |
          coverage report --fail-under=80 --show-missing --skip-empty